name: Maven Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Version att släppa (t.ex. 1.0.4)'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Klona repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Krävs för att kunna pusha taggar

      - name: Sätt upp Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'

      - name: Git användarinfo
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Sätt release-version i pom.xml
        run: |
          mvn versions:set -DnewVersion=${{ github.event.inputs.release_version }} -DgenerateBackupPoms=false

      - name: Commit release-version
        run: |
          git commit -am "🔖 Release version ${{ github.event.inputs.release_version }}"
          git push origin develop

      - name: Skapa tagg
        run: |
          git tag -a v${{ github.event.inputs.release_version }} -m "Release version ${{ github.event.inputs.release_version }}"
          git push origin v${{ github.event.inputs.release_version }}

      - name: Merga develop → main
        run: |
          git fetch origin
          git checkout main
          git merge origin/develop --no-ff -m "🚀 Merge release ${{ github.event.inputs.release_version }} to main"
          git push origin main

      - name: Gå tillbaka till develop och bump version
        run: |
          git checkout develop
          IFS='.' read -r MAJOR MINOR PATCH <<< "${{ github.event.inputs.release_version }}"
          NEXT_VERSION="${MAJOR}.${MINOR}.$((PATCH + 1))-SNAPSHOT"
          mvn versions:set -DnewVersion=$NEXT_VERSION -DgenerateBackupPoms=false
          git commit -am "🔧 Start next development iteration: $NEXT_VERSION"
          git push origin develop
